AllCops:
  Enabled: false
  NewCops: disable

Layout/LineLength:
  Enabled: true
  Max: 120
  AutoCorrect: true

Metrics/AbcSize:
  Enabled: true
  Max: 17

Metrics/ModuleLength:
  Enabled: true
  Max: 400

Metrics/ClassLength:
  Enabled: true
  Max: 400
  CountComments: false
  CountAsOne: []

Bundler:
  Enabled: false
Gemspec:
  Enabled: false
Lint:
  Enabled: false
Migration:
  Enabled: false
Naming:
  Enabled: false
Security:
  Enabled: false
Style:
  Enabled: false
Metrics:
  Enabled: false
Layout:
  Enabled: false
